### ISSUE TITLE
Support RKE2

### ISSUE THREAD

**Issue by olljanat** [nutanix/docker-machine#17]
**Is your feature request related to a problem? Please describe.**
Kubernetes security hardening is hard to do manually.

**Describe the solution you'd like**
[Rancher 2.6](https://github.com/rancher/rancher/releases/tag/v2.6.0) added tech preview support for [RKE2](https://docs.rke2.io/) provisioning which makes simpler to deploy security hardened Kubernetes cluster and it would be nice to have support for it on here too.

**Additional context**
Here is real world example cloud-init file which can be used to deploy RKE2 server to top of [Ubuntu cloud images](https://cloud-images.ubuntu.com/) (tested with Ubuntu 20.04 LTS) with CIS hardening template enabled.

```yaml
users:
- name: rancher
  groups:
  - sudo
  sudo: ALL=(ALL) NOPASSWD:ALL
  ssh_authorized_keys:
  - ssh-ed25519 <removed> user
  shell: /bin/bash
packages:
- net-tools
write_files:
- path: /etc/issue
  content: |2+

     **
     **
     **
     ** cloud-init is still running, please wait for the reboot..
     **
     **
     **

- path: /etc/rc.local
  permissions: "0755"
  content: |
    #!/bin/bash
    sleep 30s
    cp /etc/rancher/rke2/rke2.yaml /home/rancher/.kube/config
    chown -R rancher /home/rancher/.kube/
- path: /etc/rancher/rke2/config.yaml
  permissions: "0644"
  content: |
    profile: cis-1.6
    tls-san:
     - k8s.example.com
    node-taint:
    - "CriticalAddonsOnly=true:NoExecute"
runcmd:
- |
  curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="server" INSTALL_RKE2_VERSION="v1.21.5+rke2r2" sh -
  systemctl enable rke2-server.service

  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  rm kubectl

  mkdir /home/rancher/.kube
  useradd -r -c "etcd user" -s /sbin/nologin -M etcd
  ln -s /usr/local/share/rke2/rke2-cis-sysctl.conf /etc/sysctl.d/60-rke2-cis.conf
bootcmd:
- ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
hostname: k8s-server
manage_etc_hosts: localhost
growpart:
  mode: auto
  devices:
  - /dev/sda1
apt:
  sources: {}
power_state:
  message: Rebooting once after cloud-init has finished
  mode: reboot
```
