### ISSUE TITLE
Always need to restart the rancher-mgmt pods befor adding a new cluster

### ISSUE THREAD

**Issue by marth52** [nutanix/docker-machine#39]
### Issue
Hi there, roughly once a week, i need to restart all the rancher-mgmt pods in order to add a new downstream cluster to rancher via the nutanix driver. I added two screenshots down below in oder to demonstrate this use case. After restarting the rancher-mgmt pods, i am able to provision a new cluster.

### Nutanix Cluster Information
NCC Version: 4.5.0.2
LCM Version: 2.4.5.2
Prism Version: pc.2022.4.0.1
### Rancher Version
2.6.5
### Rancher Node Driver Version
3.2.0
### Node template
```yaml
name: worker
nutanixConfig:
    cloudInit: "#cloud-config"
    cluster: "ahv2"
    disksize: ""
    endpoint: "endpoint"
    insecure: "true"
    port: "9440"
    storageContainer: ""
    username: "user"
    vmCategories: []
    vmCpuPassthrough: "true"
    vmCores: "1"
    vmCpus: "16"
    vmImageSize: "100"
    vmImage: "k8s-base-image"
    vmMem: "65536"
    vmNetwork: [
        "subneta",
        "subnetb"    
        ]
    vmSerialPort: "false"
labels:
    zone: ahv2
```
### Expected Behavior
![image](https://user-images.githubusercontent.com/113519909/190406920-21d3763d-7c1f-4408-866a-994d7f204e5c.png)
### Actual Behavior
![image](https://user-images.githubusercontent.com/113519909/190406956-3c938df5-2d97-4a00-b493-b04635f178b8.png)

### Important Factors
<!--- Are there anything atypical about your accounts that we should know? --- >
​
