### ISSUE TITLE
Rancher time out - Used to be able to build rancher clusters there

### ISSUE THREAD

**Issue by eyanez111** [nutanix/docker-machine#41]
### Rancher Version

2.6.8
### Rancher Node Driver Version

https://github.com/nutanix/docker-machine/releases/download/v3.1.0/docker-machine-driver-nutanix_v3.1.0_linux |  

### Node template

```yaml
# Copy-paste your Node template here
{
"amazonec2Config": null,
"annotations": {
"ownerBindingsCreated": "true"
},
"baseType": "nodeTemplate",
"cloudCredentialId": null,
"created": "2022-09-12T20:57:33Z",
"createdTS": 1663016253000,
"creatorId": "user-zslj4",
"driver": "nutanix",
"engineEnv": { },
"engineInstallURL": ["https://releases.rancher.com/install-docker/20.10.sh"](https://releases.rancher.com/install-docker/20.10.sh),
"engineLabel": { },
"engineOpt": { },
"engineRegistryMirror": [ ],
"id": ["cattle-global-nt:nt-sfb56"](https://rancherdev.rd.zedev.net/v3/nodeTemplates/cattle-global-nt:nt-sfb56),
"labels": {
"cattle.io/creator": "norman"
},
"links": {
"nodePools": ["…/v3/nodePools?nodeTemplateId=cattle-global-nt%3Ant-sfb56"](https://rancherdev.rd.zedev.net/v3/nodePools?nodeTemplateId=cattle-global-nt%3Ant-sfb56),
"nodes": ["…/v3/nodes?nodeTemplateId=cattle-global-nt%3Ant-sfb56"](https://rancherdev.rd.zedev.net/v3/nodes?nodeTemplateId=cattle-global-nt%3Ant-sfb56),
"remove": ["…/v3/nodeTemplates/cattle-global-nt:nt-sfb56"](https://rancherdev.rd.zedev.net/v3/nodeTemplates/cattle-global-nt:nt-sfb56),
"self": ["…/v3/nodeTemplates/cattle-global-nt:nt-sfb56"](https://rancherdev.rd.zedev.net/v3/nodeTemplates/cattle-global-nt:nt-sfb56),
"update": ["…/v3/nodeTemplates/cattle-global-nt:nt-sfb56"](https://rancherdev.rd.zedev.net/v3/nodeTemplates/cattle-global-nt:nt-sfb56)
},
"name": "NTX-Dev-Rancher-Clusters",
"nutanixConfig": {
"cloudInit": "#cloud-config\nruncmd:\n- yum update -y\n- systemctl enable --now iscsid\npackage_upgrade: true\npackages:\n- iscsi-initiator-utils\n- nfs-utils\nusers:\n- 
"cluster": "NTX-DEV",
"diskSize": "0",
"endpoint": "ntx-dev.zepower.com",
"insecure": true,
"port": "9440",
"storageContainer": "",
"username": "francisco.yanez@zepower.com",
"vmCategories": [ ],
"vmCores": "1",
"vmCpuPassthrough": true,
"vmCpus": "4",
"vmImage": "CentOS-7-x86_64-GenericCloud-1907",
"vmImageSize": "40",
"vmMem": "8192",
"vmNetwork": [
"Software Development Apps (VLAN 125)"
]
},
"principalId": "local://user-zslj4",
"state": "active",
"transitioning": "no",
"transitioningMessage": "",
"type": ["nodeTemplate"](https://rancherdev.rd.zedev.net/v3/schemas/nodeTemplate),
"useInternalIpAddress": true,
"uuid": "2fce90de-c911-440d-acc8-afef8fc5661b"
}

```

### Expected Behavior

creation of a VM
### Actual Behavior

Error creating machine: Error in driver during machine creation: Post "https://ntx-dev.zepower.com:9440/api/nutanix/v3/clusters/list": dial tcp 172.20.10.110:9440: connect: connection timed out:Timeout waiting for ssh key

### Important Factors

We have been using Nutanix with Rancher in prod and pre prod for almost a year. We use to be able to connect to this cluster, it is a dev Nutanix cluster so we do not connect that often but this week I needed to create a cluster and I am getting this error. This was something that we used to do without a problem a few months a go.
